### ISSUE TITLE
Typo in linked blogpost 

### ISSUE THREAD

**Issue by ferologics** [eivind88/dankenstein#1]
not `Markup Chains` but `Markov Chains`

<img width="729" alt="image" src="https://user-images.githubusercontent.com/5576161/43975159-04396ef4-9cdd-11e8-9617-bfc0972a21d7.png">

**Comment by EivindArvesen** [comment]
Fixed!
Thanks :)

**Comment by ferologics** [comment]
Thanks for the blog post ☺️
